### ISSUE TITLE
How do I do this

### ISSUE THREAD

**Issue by fnfporterhi** [Mr-funkinguy/Better-FPS-For-Html-Chromebooks#1]
Every time I do it it says cannot import source, and can you help me?

**Comment by fnfporterhi** [comment]
This is what I get whenever i input it into code
please help
![Screenshot 2022-04-20 6 41 59 PM](https://user-images.githubusercontent.com/99343223/164336703-9ba70617-3cd8-4da9-a46b-e3c8fe3b6413.png)

**Comment by fnfporterhi** [comment]
DUDE ARE YOU EVEN GOING TO FUCKING HELP? YOU DIDNT EVEN RESPOND OR FIX IT, FIX THE FUCKIN THING

**Comment by Mr-funkinguy** [comment]
This Was Made As A joke to my friend forgot to make it private

**Comment by Mr-funkinguy** [comment]
It Wont Work Sorry

**Comment by fnfporterhi** [comment]
Oh sorry
